cabcom/frontend/urls.py
from django.conf.urls import patterns, url
from cabcom.frontend.cabrio.views import CabrioView

urlpatterns = patterns('',
	url(r'^cabrio/$', CabrioView.as_view(), name='cabrio'),
)

cabcom/gamelist/urls.py
from django.conf.urls import patterns, url
from cabcom.gamelist.views import IndexView, GameListView, DataListView, GameDetailView, DataDetailView, GameImportView, GamePopulateView

urlpatterns = patterns('',
	url(r'^$', IndexView.as_view(), name='index'),
	url(r'^data/$', DataListView.as_view(), name='data'),
	url(r'^data/(?P<pk>\d+)/$', DataDetailView.as_view(), name='data-detail'),
	url(r'^game/$', GameListView.as_view(), name='game'),
	url(r'^game/(?P<pk>\d+)/$', GameDetailView.as_view(), name='game-detail'),
	url(r'^import/$', GameImportView.as_view(), name='import'),
	url(r'^populate/$', GamePopulateView.as_view(), name='populate'),
)

cabcom/provider/urls.py
from django.conf.urls import patterns, url
from cabcom.provider.views import BackgroundIndexView, ScreenshotIndexView, TitleIndexView, VideoIndexView
from cabcom.provider.mame.views import MameView

urlpatterns = patterns('',
	url(r'^mame/$', MameView.as_view(), name='mame'),
	url(r'^background/$', BackgroundIndexView.as_view(), name='background'),
	url(r'^screenshot/$', ScreenshotIndexView.as_view(), name='screenshot'),
	url(r'^title/$', TitleIndexView.as_view(), name='title'),
	url(r'^video/$', VideoIndexView.as_view(), name='video'),
)

cabcom/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', include('cabcom.dashboard.urls', namespace='dashboard')),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^frontend/', include('cabcom.frontend.urls', namespace='frontend')),
	url(r'^gamelist/', include('cabcom.gamelist.urls', namespace='gamelist')),
	url(r'^login/', include('cabcom.login.urls', namespace='login')),
	url(r'^provider/', include('cabcom.provider.urls', namespace='provider')),
)

templates/base.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<title>{% block title %}{% endblock %}</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static "bootstrap/css/bootstrap.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "bootstrap/css/bootstrap-theme.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/custom.css" %}" />
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body role="document">
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'dashboard:index' %}">Cabcom</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="{% if menu_active == 'home' %}active{% endif %}"><a href="{% url 'dashboard:index' %}">Home</a></li>
          <li class="dropdown{% if menu_active == 'game' %} active{% endif %}">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Games <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'gamelist:index' %}game/">List</a></li>
              <li><a href="{% url 'gamelist:import' %}">Import</a></li>
              <li><a href="{% url 'gamelist:populate' %}">Populate</a></li>
            </ul>
          </li>
          <li class="dropdown{% if menu_active == 'data' %} active{% endif %}">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Database <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'gamelist:index' %}data/">List</a></li>
              <li class="divider"></li>
              <li class="dropdown-header">Data Sources</li>
              <li><a href="{% url 'provider:mame' %}">MAME</a></li>
            </ul>
          </li>
          <li class="dropdown{% if menu_active == 'resources' %} active{% endif %}">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Media <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'provider:title' %}"><span class="glyphicon glyphicon-tag"></span> Titles</a></li>
              <li><a href="{% url 'provider:screenshot' %}"><span class="glyphicon glyphicon-camera"></span> Screenshots</a></li>
              <li><a href="{% url 'provider:background' %}"><span class="glyphicon glyphicon-picture"></span> Backgrounds</a></li>
              <li><a href="{% url 'provider:video' %}"><span class="glyphicon glyphicon-film"></span> Videos</a></li>
            </ul>
          </li>
          <li class="dropdown{% if menu_active == 'frontend' %} active{% endif %}">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Front Ends <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'frontend:cabrio' %}"><span class="glyphicon glyphicon-star-empty"></span> Cabrio</a></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown{% if menu_active == 'admin' %} active{% endif %}">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Name <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#">Log out</a></li>
              <li class="divider"></li>
              <li><a href="{% url "admin:index" %}">Admin</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container" role="main">
    <div class="page-header">
      <h1>{% block content_title %}{% endblock %}</h1>
    </div>
    <div>
      {% block content %}
      {{ content }}
      {% endblock %}
    </div>
  </div>

  <script type="text/javascript" src="{% static "js/jquery.js" %}"></script>
  <script type="text/javascript" src="{% static "bootstrap/js/bootstrap.js" %}"></script>
</body>
</html>